Added plugin files
cenchat/cenchat-wordpress-plugin pull request #1
Opened 2018-05-02 03:57 UTC by phedamian

For code review

2018-05-02 07:17 UTC, mikkopaderes requested changes

2018-05-02 07:17 UTC, mikkopaderes commented on cenchat.php
> +/*
Looking [here](https://developer.wordpress.org/plugins/the-basics/including-a-software-license/). Let's change this to be:

```php
/*
Plugin Name: Cenchat
Plugin URI: https://github.com/cenchat/cenchat-wordpress-plugin/
Description: WordPress plugin for integrating Cenchat
Version: v0.0.1
Author: Cenchat and various contributors
Author URI: https://github.com/cenchat/cenchat-wordpress-plugin/graphs/contributors
License: GPL-3.0
License URI: https://github.com/cenchat/cenchat-wordpress-plugin/blob/master/LICENSE

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
```

2018-05-02 07:17 UTC, mikkopaderes commented on cenchat.php
> +register_activation_hook( __FILE__, 'activate_cenchat' );
Add a new line after every function declaration

2018-05-02 07:17 UTC, mikkopaderes commented on cenchat.php
> +    $activator = new Cenchat_Activator();
I personally like to have a blank line separation for assignments and function calls. Please add a blank line before and after this.

2018-05-02 07:17 UTC, mikkopaderes commented on cenchat.php
> +run_cenchat();
Add a blank line before this. Also, as a convention, all files should have an empty blank line at the end. Please add those in all your files.

2018-05-02 07:17 UTC, mikkopaderes commented on includes/cenchat-activator.php
> +
I think you got this new line after a `class` in the boilerplate. WordPress doesn't have an opinion for this but PSR does. Let's remove these blank lines in all our class. Same goes for the blank lines before the closing curly-braces of a `class`.

2018-05-02 07:17 UTC, mikkopaderes commented on includes/cenchat-activator.php
> +            update_option( 'cenchat_id', $arr );
Nitpicking, let's add a new line before this function call.

2018-05-02 07:17 UTC, rmmmp commented on includes/cenchat-comments.php
> +}
Add a blank line at the end of file

2018-05-02 07:17 UTC, rmmmp commented on includes/cenchat-meta.php
> +?>
I think we should remove this closing `?>

2018-05-02 07:17 UTC, rmmmp commented on includes/cenchat-settings.php
> +?>
I think we should remove this `?>`

2018-05-02 07:17 UTC, rmmmp commented on includes/template.php
> +<?php endif; ?>
Add a blank line

2018-05-02 07:18 UTC, rmmmp commented
@phedamian can you also add a screenshot showing what the plugin settings would look like in the admin dashboard? Thanks!

2018-05-02 08:37 UTC, mikkopaderes requested changes

2018-05-02 08:37 UTC, rmmmp commented on includes/cenchat-meta.php
> +        <meta property="cenchat:id" content="<?php echo $options['id_text']; ?>">
Can we move this to `public/partials/` folder? I think a regular function that accepts the `$options['idx_text']` would suffice.

2018-05-02 08:37 UTC, rmmmp commented on includes/cenchat-settings.php
> +        echo "<input id='cenchat_id_text' name='cenchat_id[id_text]' size='40' type='text' value='{$options['id_text']}'>";
Can we move this to `admin/partials/` folder? I think a regular function that accepts the necessary params would suffice.

2018-05-02 08:37 UTC, rmmmp commented on includes/cenchat-settings.php
> +        <div class="wrap">
Can we move this to `admin/partials` folder? I think a regular function that accepts the necessary params would suffice.

2018-05-02 08:37 UTC, rmmmp commented on includes/template.php
> +<?php if (comments_open()) : ?>
Can we move this to `public/partials/` folder?

2018-05-02 13:58 UTC, mikkopaderes requested changes

2018-05-02 13:58 UTC, rmmmp commented on admin/partials/settings.php
> +<?php ?>
Should this be `<?php`?

2018-05-02 13:58 UTC, rmmmp commented on admin/partials/settings.php
> +<?php ?>
Should this be `?>`

2018-05-02 13:58 UTC, rmmmp commented on includes/cenchat-comments.php
> +        return dirname( dirname( __FILE__ ) ) . '/public/partials/template.php';
Use [`plugin_dir_path`](https://developer.wordpress.org/reference/functions/plugin_dir_path/) instead of nested `dirname()`.

2018-05-02 13:58 UTC, rmmmp commented on includes/cenchat-meta.php
> +        require_once dirname( dirname( __FILE__ ) ) . '/public/partials/meta.php';
Use [`plugin_dir_path`](https://developer.wordpress.org/reference/functions/plugin_dir_path/) instead of nested `dirname()`.

2018-05-02 13:58 UTC, rmmmp commented on public/partials/meta.php
> +<?php ?>
Should this be `<?php`?

2018-05-02 13:58 UTC, rmmmp commented on public/partials/meta.php
> +<?php ?>
Should this be `?>`?

2018-05-02 13:58 UTC, rmmmp commented on admin/partials/input.php
> +    echo "<input id='cenchat_id_text' name='cenchat_id[id_text]' size='40' type='text' value='{$options['id_text']}'>";
Do we still need `echo` here? Can't we place the HTML codes itself?

2018-05-03 07:11 UTC, mikkopaderes requested changes

2018-05-03 07:11 UTC, rmmmp commented on includes/cenchat-comments.php
> +        return plugin_dir_path( plugin_dir_path( __FILE__ ) ) . '/public/partials/template.php';
This should be `plugin_dir_path( dirname( __FILE__ ) )`

2018-05-03 07:11 UTC, rmmmp commented on includes/cenchat-meta.php
> +        require_once plugin_dir_path( plugin_dir_path( __FILE__ ) ) . '/public/partials/meta.php';
This should be `plugin_dir_path( dirname( __FILE__ ) )`

2018-05-03 07:11 UTC, rmmmp commented on includes/cenchat-settings.php
> +        require_once plugin_dir_path( plugin_dir_path( __FILE__ ) ) . '/admin/partials/input.php';
This should be `plugin_dir_path( dirname( __FILE__ ) )`

2018-05-03 07:11 UTC, rmmmp commented on includes/cenchat-settings.php
> +        require_once plugin_dir_path( plugin_dir_path( __FILE__ ) ) . '/admin/partials/settings.php';
This should be `plugin_dir_path( dirname( __FILE__ ) )`

2018-05-03 15:07 UTC, mikkopaderes approved these changes

2018-05-03 15:08 UTC, merged

2018-05-03 15:08 UTC, rmmmp commented
@phedamian - Much awesome. Very thanks. It ships. :shipit: